// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func DeletionRequests() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"user-management\" x-data=\"userListComponent\" x-init=\"loadUsers\" class=\"h-full flex flex-col\"><!-- Header --><div class=\"p-4 border-b\"><h2 class=\"text-xl font-semibold\">User Management</h2><button x-on:click=\"refreshUsers\" x-bind:disabled=\"loading\" class=\"mt-2 px-4 py-2 bg-blue-500 text-white rounded\"><span x-show=\"!loading\">Refresh</span> <span x-show=\"loading\">Loading...</span></button></div><!-- Error display --><div x-show=\"error\" x-text=\"error\" class=\"p-4 bg-red-100 text-red-700\"></div><!-- User list --><div class=\"flex-1 overflow-y-auto\" x-on:scroll=\"checkScroll\"><template x-for=\"user in users\"><div class=\"p-4 border-b flex justify-between items-center\"><div><div class=\"font-medium\" x-text=\"user.name\"></div><div class=\"text-gray-600\" x-text=\"user.email\"></div></div><button x-on:click=\"deleteUser\" x-bind:data-user-id=\"user.id\" class=\"px-3 py-1 bg-red-500 text-white rounded hover:bg-red-600\">Delete</button></div></template><!-- Loading indicator for pagination --><div x-show=\"loadingMore\" class=\"p-4 text-center\">Loading more users...</div><!-- End of data indicator --><div x-show=\"endOfData\" class=\"p-4 text-center text-gray-500\">No more users to load</div><!-- Empty state --><div x-show=\"isEmpty\" class=\"p-8 text-center text-gray-500\">No users found</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
